export const mockVaults = [
  {
    id: 1,
    name: "USDC Fortress",
    asset: "USDC",
    apy: 12.5,
    tvl: 2450000,
    risk: "LOW" as const,
    privacyLevel: 5,
    description: "Ultra-secure stablecoin vault with ZK-shielded deposits",
    yieldSources: ["Aave", "Compound", "Curve"],
  },
  {
    id: 2,
    name: "ETH Shield",
    asset: "ETH",
    apy: 8.3,
    tvl: 1850000,
    risk: "MEDIUM" as const,
    privacyLevel: 4,
    description: "Privacy-first Ethereum staking with liquid rewards",
    yieldSources: ["Lido", "Rocket Pool"],
  },
  {
    id: 3,
    name: "MATIC Guardian",
    asset: "MATIC",
    apy: 15.7,
    tvl: 980000,
    risk: "MEDIUM" as const,
    privacyLevel: 4,
    description: "Native Polygon staking with AI optimization",
    yieldSources: ["Polygon Staking", "QuickSwap"],
  },
  {
    id: 4,
    name: "USDT Citadel",
    asset: "USDT",
    apy: 11.2,
    tvl: 1650000,
    risk: "LOW" as const,
    privacyLevel: 5,
    description: "Rock-solid Tether vault with cross-protocol yield",
    yieldSources: ["Aave", "Curve"],
  },
  {
    id: 5,
    name: "High Yield Alpha",
    asset: "MULTI",
    apy: 28.9,
    tvl: 520000,
    risk: "HIGH" as const,
    privacyLevel: 3,
    description: "Aggressive multi-asset strategy for maximum yields",
    yieldSources: ["Multiple DEXs", "Lending Protocols"],
  },
  {
    id: 6,
    name: "BTC Vault",
    asset: "WBTC",
    apy: 6.8,
    tvl: 3200000,
    risk: "LOW" as const,
    privacyLevel: 5,
    description: "Wrapped Bitcoin with conservative DeFi strategies",
    yieldSources: ["Compound", "Aave"],
  },
];

export const mockPortfolio = {
  totalBalance: 12458.32,
  change24h: 3.25,
  activePositions: 3,
  pendingRewards: 45.67,
  positions: [
    {
      vault: "USDC Fortress",
      deposited: 5000,
      currentValue: 5156.25,
      apy: 12.5,
      status: "Active",
    },
    {
      vault: "ETH Shield",
      deposited: 3.2,
      currentValue: 7185.44,
      apy: 8.3,
      status: "Active",
    },
    {
      vault: "MATIC Guardian",
      deposited: 2500,
      currentValue: 2616.63,
      apy: 15.7,
      status: "Active",
    },
  ],
};

export const mockTransactions = [
  {
    id: 1,
    type: "Deposit",
    vault: "USDC Fortress",
    amount: 5000,
    asset: "USDC",
    timestamp: new Date("2025-01-20T14:30:00"),
    status: "COMPLETED" as const,
    txHash: "0x1234...5678",
  },
  {
    id: 2,
    type: "Claim Rewards",
    vault: "ETH Shield",
    amount: 0.025,
    asset: "ETH",
    timestamp: new Date("2025-01-19T09:15:00"),
    status: "COMPLETED" as const,
    txHash: "0xabcd...efgh",
  },
  {
    id: 3,
    type: "Deposit",
    vault: "MATIC Guardian",
    amount: 2500,
    asset: "MATIC",
    timestamp: new Date("2025-01-18T16:45:00"),
    status: "COMPLETED" as const,
    txHash: "0x9876...5432",
  },
  {
    id: 4,
    type: "Withdraw",
    vault: "USDT Citadel",
    amount: 1000,
    asset: "USDT",
    timestamp: new Date("2025-01-17T11:20:00"),
    status: "PENDING" as const,
    txHash: "0xdef0...1234",
  },
];

export const mockProposals = [
  {
    id: 1,
    title: "Increase AI Optimization Frequency",
    description: "Proposal to increase automated rebalancing from daily to every 6 hours for better yield capture",
    votesFor: 12500000,
    votesAgainst: 3200000,
    votesAbstain: 1800000,
    deadline: new Date("2025-01-30T00:00:00"),
    status: "Active",
  },
  {
    id: 2,
    title: "Add Support for Arbitrum Vaults",
    description: "Expand Nexus Protocol to support vault deployments on Arbitrum network",
    votesFor: 8900000,
    votesAgainst: 2100000,
    votesAbstain: 950000,
    deadline: new Date("2025-02-05T00:00:00"),
    status: "Active",
  },
  {
    id: 3,
    title: "Treasury Diversification",
    description: "Diversify protocol treasury into BTC, ETH, and stablecoins (40/30/30 split)",
    votesFor: 15200000,
    votesAgainst: 4800000,
    votesAbstain: 2200000,
    deadline: new Date("2025-01-25T00:00:00"),
    status: "Active",
  },
];

export const mockAIRecommendations = [
  {
    title: "Move 40% USDC to High Yield Alpha",
    apy: "+5.2%",
    risk: "MEDIUM" as const,
    reason: "Current market conditions favor aggressive DeFi strategies",
  },
  {
    title: "Stake ETH in Shield Vault",
    apy: "+3.8%",
    risk: "LOW" as const,
    reason: "Upcoming merge will boost staking rewards",
  },
  {
    title: "Compound MATIC rewards automatically",
    apy: "+2.1%",
    risk: "LOW" as const,
    reason: "Auto-compounding increases APY by 2.1% annually",
  },
];

export const mockStealthTransactions = [
  {
    id: 1,
    type: "Sent",
    toFrom: "@alice",
    amount: 500,
    asset: "USDC",
    timestamp: new Date("2025-01-20T10:30:00"),
    status: "COMPLETED" as const,
    txHash: "0xstealth1...abc",
    privacyLevel: 5,
  },
  {
    id: 2,
    type: "Received",
    toFrom: "@bob",
    amount: 250,
    asset: "USDT",
    timestamp: new Date("2025-01-19T15:45:00"),
    status: "COMPLETED" as const,
    txHash: "0xstealth2...def",
    privacyLevel: 5,
  },
];
